### PR TITLE
adds server name fix.

### PR DESCRIPTION
**Pull request by singh1114**
server name error is fixed now we can log in just by using the name(without server address). gnewhatsapp.html is created for the furthur general changes.

### CODE REVIEW

**Comment by amrit3701** [comment]
If gnewhatsapp.html is the main page, then rename it with index.html.

**Comment by singh1114** [comment]
OK. But should we keep index.html for future references or delete it.

**Comment by singh1114** [comment]
Done.

**Comment by amrit3701** [comment]
Replace 'user@server' to 'user' in the login box.

**Comment by singh1114** [comment]
user@servername changed to Username.

**Pull request merged**
